-- OTea x GreyOne - editable menu and modifiers
--
-- Moves the menu out of server.js so staff can change it without a deploy, and
-- makes modifiers real records instead of hardcoded conditionals. This is also
-- the foundation for two later features:
--   * company attribution hangs off the category (line-item revenue split)
--   * recipes will hang off menu items (ingredient depletion)
--
-- Safe to re-run.

-- ---------------------------------------------------------------
-- Companies. Revenue splits by line item via the item's category.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS companies (
  id   SMALLINT PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL
);

INSERT INTO companies (id, code, name) VALUES
  (1, 'OTEA',    'OTea'),
  (2, 'GREYONE', 'GreyOne')
ON CONFLICT (id) DO NOTHING;

-- ---------------------------------------------------------------
-- Categories
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS menu_categories (
  id         SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL UNIQUE,
  name_zh    TEXT,
  company_id SMALLINT NOT NULL REFERENCES companies(id),
  sort_order SMALLINT NOT NULL DEFAULT 0,
  is_active  BOOLEAN  NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------
-- Items and their size/type variants
--
-- Ids are explicit rather than generated: existing order_items rows already
-- reference these numbers, and the sequence is realigned after seeding.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS menu_items (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id SMALLINT NOT NULL REFERENCES menu_categories(id),
  name        TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  image_url   TEXT,
  sort_order  SMALLINT NOT NULL DEFAULT 0,
  is_active   BOOLEAN  NOT NULL DEFAULT TRUE,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS menu_variants (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id    INTEGER NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
  name       TEXT NOT NULL,
  price      NUMERIC(10,2) NOT NULL CHECK (price >= 0),
  sort_order SMALLINT NOT NULL DEFAULT 0,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE
);

-- ---------------------------------------------------------------
-- Modifiers
--
-- selection = 'single' renders as a pill row (ice, sugar, matcha grade);
-- 'multi' renders as toggles (crystal boba, extra shot). price_delta is added
-- per unit, and is 0 for choices like sugar level that do not cost anything.
-- ---------------------------------------------------------------
CREATE TABLE IF NOT EXISTS modifier_groups (
  id         SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       TEXT NOT NULL,
  name_zh    TEXT,
  selection  TEXT NOT NULL DEFAULT 'single' CHECK (selection IN ('single','multi')),
  is_required BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order SMALLINT NOT NULL DEFAULT 0,
  is_active  BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS modifier_options (
  id          SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id    SMALLINT NOT NULL REFERENCES modifier_groups(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  name_zh     TEXT,
  price_delta NUMERIC(10,2) NOT NULL DEFAULT 0,
  is_default  BOOLEAN NOT NULL DEFAULT FALSE,
  sort_order  SMALLINT NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT TRUE
);

-- A group reaches drinks either through a whole category (ice, sugar, boba)
-- or pinned to one item (the lemon tea base choice).
CREATE TABLE IF NOT EXISTS category_modifier_groups (
  category_id SMALLINT NOT NULL REFERENCES menu_categories(id) ON DELETE CASCADE,
  group_id    SMALLINT NOT NULL REFERENCES modifier_groups(id) ON DELETE CASCADE,
  PRIMARY KEY (category_id, group_id)
);

CREATE TABLE IF NOT EXISTS item_modifier_groups (
  item_id  INTEGER  NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
  group_id SMALLINT NOT NULL REFERENCES modifier_groups(id) ON DELETE CASCADE,
  PRIMARY KEY (item_id, group_id)
);

CREATE INDEX IF NOT EXISTS idx_items_category   ON menu_items (category_id);
CREATE INDEX IF NOT EXISTS idx_variants_item    ON menu_variants (item_id);
CREATE INDEX IF NOT EXISTS idx_options_group    ON modifier_options (group_id);

-- Same lockdown as the order tables: PostgREST is denied, the app connects as
-- the owner and bypasses RLS.
ALTER TABLE companies               ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_categories         ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_items              ENABLE ROW LEVEL SECURITY;
ALTER TABLE menu_variants           ENABLE ROW LEVEL SECURITY;
ALTER TABLE modifier_groups         ENABLE ROW LEVEL SECURITY;
ALTER TABLE modifier_options        ENABLE ROW LEVEL SECURITY;
ALTER TABLE category_modifier_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE item_modifier_groups    ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON companies, menu_categories, menu_items, menu_variants,
              modifier_groups, modifier_options, category_modifier_groups,
              item_modifier_groups
  FROM anon, authenticated;
